all: ch11triangle ch11tree ch11reals

ch11triangle: ch11triangle.c errprint.h
	gcc -o ch11triangle ch11triangle.c

ch11tree: ch11tree.c errprint.h
	gcc -o ch11tree ch11tree.c

ch11reals: ch11reals.c errprint.h
	gcc -o ch11reals ch11reals.c